name: Build Armbian

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Start Build
        run: |
          sudo -E ./compile.sh BUILD_MINIMAL=yes KERNEL_ONLY=no KERNEL_CONFIGURE=no BOARD=allwinner-h6-tv RELEASE=focal BUILD_DESKTOP=no 
          tar -czvf armbian-tv-allwinner-h6.img.gz output/images/*.img
          
      - name: Upload Armbian image
        uses: actions/upload-artifact@master
        with:
          name: armbian-tv-allwinner-h6.img.gz
          path: armbian-tv-allwinner-h6.img.gz
